name: sql database
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
      - name: test-output
        run: |
          echo "Hello, World!"
          echo "This is a test output."
        
  remote-connect:
    runs-on: ubuntu-latest
    steps:
      - name: remote-connect
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        mkdir -p backup
        mysqldump -h "$DB_HOST" --port 3306 -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" > backup/${DB_NAME}_$(date +%F).sql